import csv

# Major airports in US and Canada with IATA codes and coordinates
major_airports = [
    # US Major Airports
    {'IATA': 'ATL', 'Name': 'Hartsfield-Jackson Atlanta International', 'City': 'Atlanta', 'State': 'GA', 'Country': 'United States', 'Latitude': '33.6407', 'Longitude': '-84.4277'},
    {'IATA': 'LAX', 'Name': 'Los Angeles International', 'City': 'Los Angeles', 'State': 'CA', 'Country': 'United States', 'Latitude': '33.9425', 'Longitude': '-118.4081'},
    {'IATA': 'ORD', 'Name': "O'Hare International", 'City': 'Chicago', 'State': 'IL', 'Country': 'United States', 'Latitude': '41.9786', 'Longitude': '-87.9048'},
    {'IATA': 'DFW', 'Name': 'Dallas/Fort Worth International', 'City': 'Dallas', 'State': 'TX', 'Country': 'United States', 'Latitude': '32.8969', 'Longitude': '-97.0381'},
    {'IATA': 'DEN', 'Name': 'Denver International', 'City': 'Denver', 'State': 'CO', 'Country': 'United States', 'Latitude': '39.8617', 'Longitude': '-104.6731'},
    {'IATA': 'JFK', 'Name': 'John F. Kennedy International', 'City': 'New York', 'State': 'NY', 'Country': 'United States', 'Latitude': '40.6413', 'Longitude': '-73.7781'},
    {'IATA': 'SFO', 'Name': 'San Francisco International', 'City': 'San Francisco', 'State': 'CA', 'Country': 'United States', 'Latitude': '37.6213', 'Longitude': '-122.3790'},
    {'IATA': 'SEA', 'Name': 'Seattle-Tacoma International', 'City': 'Seattle', 'State': 'WA', 'Country': 'United States', 'Latitude': '47.4502', 'Longitude': '-122.3088'},
    {'IATA': 'LAS', 'Name': 'McCarran International', 'City': 'Las Vegas', 'State': 'NV', 'Country': 'United States', 'Latitude': '36.0840', 'Longitude': '-115.1537'},
    {'IATA': 'MIA', 'Name': 'Miami International', 'City': 'Miami', 'State': 'FL', 'Country': 'United States', 'Latitude': '25.7959', 'Longitude': '-80.2870'},
    {'IATA': 'CLT', 'Name': 'Charlotte Douglas International', 'City': 'Charlotte', 'State': 'NC', 'Country': 'United States', 'Latitude': '35.2144', 'Longitude': '-80.9473'},
    {'IATA': 'PHX', 'Name': 'Phoenix Sky Harbor International', 'City': 'Phoenix', 'State': 'AZ', 'Country': 'United States', 'Latitude': '33.4342', 'Longitude': '-112.0116'},
    {'IATA': 'EWR', 'Name': 'Newark Liberty International', 'City': 'Newark', 'State': 'NJ', 'Country': 'United States', 'Latitude': '40.6895', 'Longitude': '-74.1745'},
    {'IATA': 'IAH', 'Name': 'George Bush Intercontinental', 'City': 'Houston', 'State': 'TX', 'Country': 'United States', 'Latitude': '29.9902', 'Longitude': '-95.3368'},
    {'IATA': 'MCO', 'Name': 'Orlando International', 'City': 'Orlando', 'State': 'FL', 'Country': 'United States', 'Latitude': '28.4312', 'Longitude': '-81.3083'},
    {'IATA': 'MSP', 'Name': 'Minneapolis-Saint Paul International', 'City': 'Minneapolis', 'State': 'MN', 'Country': 'United States', 'Latitude': '44.8848', 'Longitude': '-93.2223'},
    {'IATA': 'DTW', 'Name': 'Detroit Metropolitan', 'City': 'Detroit', 'State': 'MI', 'Country': 'United States', 'Latitude': '42.2162', 'Longitude': '-83.3554'},
    {'IATA': 'PHL', 'Name': 'Philadelphia International', 'City': 'Philadelphia', 'State': 'PA', 'Country': 'United States', 'Latitude': '39.8719', 'Longitude': '-75.2411'},
    {'IATA': 'LGA', 'Name': 'LaGuardia', 'City': 'New York', 'State': 'NY', 'Country': 'United States', 'Latitude': '40.7769', 'Longitude': '-73.8740'},
    {'IATA': 'BWI', 'Name': 'Baltimore/Washington International', 'City': 'Baltimore', 'State': 'MD', 'Country': 'United States', 'Latitude': '39.1774', 'Longitude': '-76.6684'},
    {'IATA': 'SLC', 'Name': 'Salt Lake City International', 'City': 'Salt Lake City', 'State': 'UT', 'Country': 'United States', 'Latitude': '40.7899', 'Longitude': '-111.9791'},
    {'IATA': 'DCA', 'Name': 'Ronald Reagan Washington National', 'City': 'Washington', 'State': 'DC', 'Country': 'United States', 'Latitude': '38.8512', 'Longitude': '-77.0402'},
    {'IATA': 'MDW', 'Name': 'Chicago Midway International', 'City': 'Chicago', 'State': 'IL', 'Country': 'United States', 'Latitude': '41.7868', 'Longitude': '-87.7522'},
    {'IATA': 'HNL', 'Name': 'Daniel K. Inouye International', 'City': 'Honolulu', 'State': 'HI', 'Country': 'United States', 'Latitude': '21.3206', 'Longitude': '-157.9242'},
    {'IATA': 'ANC', 'Name': 'Ted Stevens Anchorage International', 'City': 'Anchorage', 'State': 'AK', 'Country': 'United States', 'Latitude': '61.1743', 'Longitude': '-149.9962'},
    {'IATA': 'BOS', 'Name': 'Logan International', 'City': 'Boston', 'State': 'MA', 'Country': 'United States', 'Latitude': '42.3656', 'Longitude': '-71.0096'},
    {'IATA': 'IAD', 'Name': 'Washington Dulles International', 'City': 'Washington', 'State': 'VA', 'Country': 'United States', 'Latitude': '38.9531', 'Longitude': '-77.4565'},
    {'IATA': 'FLL', 'Name': 'Fort Lauderdale-Hollywood International', 'City': 'Fort Lauderdale', 'State': 'FL', 'Country': 'United States', 'Latitude': '26.0726', 'Longitude': '-80.1528'},
    {'IATA': 'PDX', 'Name': 'Portland International', 'City': 'Portland', 'State': 'OR', 'Country': 'United States', 'Latitude': '45.5898', 'Longitude': '-122.5951'},
    {'IATA': 'STL', 'Name': 'St. Louis Lambert International', 'City': 'St. Louis', 'State': 'MO', 'Country': 'United States', 'Latitude': '38.7487', 'Longitude': '-90.3700'},
    {'IATA': 'SAN', 'Name': 'San Diego International', 'City': 'San Diego', 'State': 'CA', 'Country': 'United States', 'Latitude': '32.7338', 'Longitude': '-117.1933'},
    {'IATA': 'TPA', 'Name': 'Tampa International', 'City': 'Tampa', 'State': 'FL', 'Country': 'United States', 'Latitude': '27.9755', 'Longitude': '-82.5332'},
    {'IATA': 'BNA', 'Name': 'Nashville International', 'City': 'Nashville', 'State': 'TN', 'Country': 'United States', 'Latitude': '36.1245', 'Longitude': '-86.6782'},
    {'IATA': 'AUS', 'Name': 'Austin-Bergstrom International', 'City': 'Austin', 'State': 'TX', 'Country': 'United States', 'Latitude': '30.1945', 'Longitude': '-97.6699'},
    {'IATA': 'OAK', 'Name': 'Oakland International', 'City': 'Oakland', 'State': 'CA', 'Country': 'United States', 'Latitude': '37.7213', 'Longitude': '-122.2207'},
    {'IATA': 'MSY', 'Name': 'Louis Armstrong New Orleans International', 'City': 'New Orleans', 'State': 'LA', 'Country': 'United States', 'Latitude': '29.9934', 'Longitude': '-90.2581'},
    {'IATA': 'RDU', 'Name': 'Raleigh-Durham International', 'City': 'Raleigh', 'State': 'NC', 'Country': 'United States', 'Latitude': '35.8776', 'Longitude': '-78.7875'},
    {'IATA': 'CLE', 'Name': 'Cleveland Hopkins International', 'City': 'Cleveland', 'State': 'OH', 'Country': 'United States', 'Latitude': '41.4117', 'Longitude': '-81.8498'},
    {'IATA': 'IND', 'Name': 'Indianapolis International', 'City': 'Indianapolis', 'State': 'IN', 'Country': 'United States', 'Latitude': '39.7173', 'Longitude': '-86.2944'},
    {'IATA': 'CMH', 'Name': 'John Glenn Columbus International', 'City': 'Columbus', 'State': 'OH', 'Country': 'United States', 'Latitude': '39.9980', 'Longitude': '-82.8919'},
    {'IATA': 'MCI', 'Name': 'Kansas City International', 'City': 'Kansas City', 'State': 'MO', 'Country': 'United States', 'Latitude': '39.2976', 'Longitude': '-94.7139'},
    {'IATA': 'SJC', 'Name': 'Norman Y. Mineta San Jose International', 'City': 'San Jose', 'State': 'CA', 'Country': 'United States', 'Latitude': '37.3626', 'Longitude': '-121.9290'},
    {'IATA': 'SMF', 'Name': 'Sacramento International', 'City': 'Sacramento', 'State': 'CA', 'Country': 'United States', 'Latitude': '38.6954', 'Longitude': '-121.5908'},
    {'IATA': 'PIT', 'Name': 'Pittsburgh International', 'City': 'Pittsburgh', 'State': 'PA', 'Country': 'United States', 'Latitude': '40.4915', 'Longitude': '-80.2329'},
    {'IATA': 'MKE', 'Name': 'General Mitchell International', 'City': 'Milwaukee', 'State': 'WI', 'Country': 'United States', 'Latitude': '42.9472', 'Longitude': '-87.8966'},
    {'IATA': 'BUF', 'Name': 'Buffalo Niagara International', 'City': 'Buffalo', 'State': 'NY', 'Country': 'United States', 'Latitude': '42.9405', 'Longitude': '-78.7322'},
    {'IATA': 'JAX', 'Name': 'Jacksonville International', 'City': 'Jacksonville', 'State': 'FL', 'Country': 'United States', 'Latitude': '30.4941', 'Longitude': '-81.6879'},
    {'IATA': 'BUR', 'Name': 'Hollywood Burbank', 'City': 'Burbank', 'State': 'CA', 'Country': 'United States', 'Latitude': '34.2006', 'Longitude': '-118.3587'},
    {'IATA': 'ABQ', 'Name': 'Albuquerque International Sunport', 'City': 'Albuquerque', 'State': 'NM', 'Country': 'United States', 'Latitude': '35.0402', 'Longitude': '-106.6092'},
    {'IATA': 'BOI', 'Name': 'Boise Airport', 'City': 'Boise', 'State': 'ID', 'Country': 'United States', 'Latitude': '43.5644', 'Longitude': '-116.2228'},
    {'IATA': 'OGG', 'Name': 'Kahului Airport', 'City': 'Kahului', 'State': 'HI', 'Country': 'United States', 'Latitude': '20.8986', 'Longitude': '-156.4306'},
    
    # Canadian Major Airports
    {'IATA': 'YYZ', 'Name': 'Toronto Pearson International', 'City': 'Toronto', 'State': 'ON', 'Country': 'Canada', 'Latitude': '43.6772', 'Longitude': '-79.6306'},
    {'IATA': 'YVR', 'Name': 'Vancouver International', 'City': 'Vancouver', 'State': 'BC', 'Country': 'Canada', 'Latitude': '49.1947', 'Longitude': '-123.1792'},
    {'IATA': 'YUL', 'Name': 'Montréal-Pierre Elliott Trudeau International', 'City': 'Montreal', 'State': 'QC', 'Country': 'Canada', 'Latitude': '45.4577', 'Longitude': '-73.7497'},
    {'IATA': 'YYC', 'Name': 'Calgary International', 'City': 'Calgary', 'State': 'AB', 'Country': 'Canada', 'Latitude': '51.1215', 'Longitude': '-114.0076'},
    {'IATA': 'YEG', 'Name': 'Edmonton International', 'City': 'Edmonton', 'State': 'AB', 'Country': 'Canada', 'Latitude': '53.3097', 'Longitude': '-113.5797'},
    {'IATA': 'YOW', 'Name': 'Ottawa Macdonald-Cartier International', 'City': 'Ottawa', 'State': 'ON', 'Country': 'Canada', 'Latitude': '45.3225', 'Longitude': '-75.6692'},
    {'IATA': 'YHZ', 'Name': 'Halifax Stanfield International', 'City': 'Halifax', 'State': 'NS', 'Country': 'Canada', 'Latitude': '44.8808', 'Longitude': '-63.5086'},
    {'IATA': 'YWG', 'Name': 'Winnipeg James Armstrong Richardson International', 'City': 'Winnipeg', 'State': 'MB', 'Country': 'Canada', 'Latitude': '49.9100', 'Longitude': '-97.2399'},
    {'IATA': 'YQB', 'Name': 'Québec City Jean Lesage International', 'City': 'Quebec City', 'State': 'QC', 'Country': 'Canada', 'Latitude': '46.7911', 'Longitude': '-71.3933'},
    {'IATA': 'YQR', 'Name': 'Regina International', 'City': 'Regina', 'State': 'SK', 'Country': 'Canada', 'Latitude': '50.4319', 'Longitude': '-104.6658'},
    {'IATA': 'YQT', 'Name': 'Thunder Bay International', 'City': 'Thunder Bay', 'State': 'ON', 'Country': 'Canada', 'Latitude': '48.3719', 'Longitude': '-89.3239'},
    {'IATA': 'YFC', 'Name': 'Fredericton International', 'City': 'Fredericton', 'State': 'NB', 'Country': 'Canada', 'Latitude': '45.8689', 'Longitude': '-66.5372'},
    {'IATA': 'YXY', 'Name': 'Erik Nielsen Whitehorse International', 'City': 'Whitehorse', 'State': 'YT', 'Country': 'Canada', 'Latitude': '60.7096', 'Longitude': '-135.0673'},
    {'IATA': 'YFB', 'Name': 'Iqaluit Airport', 'City': 'Iqaluit', 'State': 'NU', 'Country': 'Canada', 'Latitude': '63.7567', 'Longitude': '-68.5558'},
    
    # Indian Major Airports (International and Major Domestic)
    {'IATA': 'DEL', 'Name': 'Indira Gandhi International', 'City': 'New Delhi', 'State': 'Delhi', 'Country': 'India', 'Latitude': '28.5562', 'Longitude': '77.1000'},
    {'IATA': 'BOM', 'Name': 'Chhatrapati Shivaji Maharaj International', 'City': 'Mumbai', 'State': 'Maharashtra', 'Country': 'India', 'Latitude': '19.0896', 'Longitude': '72.8656'},
    {'IATA': 'CCU', 'Name': 'Netaji Subhas Chandra Bose International', 'City': 'Kolkata', 'State': 'West Bengal', 'Country': 'India', 'Latitude': '22.6547', 'Longitude': '88.4467'},
    {'IATA': 'MAA', 'Name': 'Chennai International', 'City': 'Chennai', 'State': 'Tamil Nadu', 'Country': 'India', 'Latitude': '12.9944', 'Longitude': '80.1806'},
    {'IATA': 'BLR', 'Name': 'Kempegowda International', 'City': 'Bangalore', 'State': 'Karnataka', 'Country': 'India', 'Latitude': '13.1986', 'Longitude': '77.7066'},
    {'IATA': 'HYD', 'Name': 'Rajiv Gandhi International', 'City': 'Hyderabad', 'State': 'Telangana', 'Country': 'India', 'Latitude': '17.2403', 'Longitude': '78.4294'},
    {'IATA': 'COK', 'Name': 'Cochin International', 'City': 'Kochi', 'State': 'Kerala', 'Country': 'India', 'Latitude': '9.9312', 'Longitude': '76.2673'},
    {'IATA': 'AMD', 'Name': 'Sardar Vallabhbhai Patel International', 'City': 'Ahmedabad', 'State': 'Gujarat', 'Country': 'India', 'Latitude': '23.0772', 'Longitude': '72.5717'},
    {'IATA': 'GOI', 'Name': 'Dabolim Airport', 'City': 'Goa', 'State': 'Goa', 'Country': 'India', 'Latitude': '15.3808', 'Longitude': '73.8314'},
    {'IATA': 'GAU', 'Name': 'Lokpriya Gopinath Bordoloi International', 'City': 'Guwahati', 'State': 'Assam', 'Country': 'India', 'Latitude': '26.1061', 'Longitude': '91.5859'},
    {'IATA': 'LKO', 'Name': 'Chaudhary Charan Singh International', 'City': 'Lucknow', 'State': 'Uttar Pradesh', 'Country': 'India', 'Latitude': '26.7606', 'Longitude': '80.8893'},
    {'IATA': 'JAI', 'Name': 'Jaipur International', 'City': 'Jaipur', 'State': 'Rajasthan', 'Country': 'India', 'Latitude': '26.8242', 'Longitude': '75.8017'},
    {'IATA': 'TRV', 'Name': 'Trivandrum International', 'City': 'Thiruvananthapuram', 'State': 'Kerala', 'Country': 'India', 'Latitude': '8.4821', 'Longitude': '76.9200'},
    {'IATA': 'BBI', 'Name': 'Biju Patnaik International', 'City': 'Bhubaneswar', 'State': 'Odisha', 'Country': 'India', 'Latitude': '20.2444', 'Longitude': '85.8178'},
    {'IATA': 'IXC', 'Name': 'Shaheed Bhagat Singh International', 'City': 'Chandigarh', 'State': 'Chandigarh', 'Country': 'India', 'Latitude': '30.6735', 'Longitude': '76.7885'},
    {'IATA': 'IXB', 'Name': 'Bagdogra Airport', 'City': 'Bagdogra', 'State': 'West Bengal', 'Country': 'India', 'Latitude': '26.6812', 'Longitude': '88.3286'},
    {'IATA': 'IXR', 'Name': 'Birsa Munda Airport', 'City': 'Ranchi', 'State': 'Jharkhand', 'Country': 'India', 'Latitude': '23.3142', 'Longitude': '85.3217'},
    {'IATA': 'VNS', 'Name': 'Lal Bahadur Shastri International', 'City': 'Varanasi', 'State': 'Uttar Pradesh', 'Country': 'India', 'Latitude': '25.4484', 'Longitude': '82.8592'},
    {'IATA': 'SXR', 'Name': 'Sheikh ul-Alam International', 'City': 'Srinagar', 'State': 'Jammu and Kashmir', 'Country': 'India', 'Latitude': '33.9871', 'Longitude': '74.7742'},
    {'IATA': 'ATQ', 'Name': 'Sri Guru Ram Dass Jee International', 'City': 'Amritsar', 'State': 'Punjab', 'Country': 'India', 'Latitude': '31.7096', 'Longitude': '74.7973'},
    {'IATA': 'IXE', 'Name': 'Mangalore International', 'City': 'Mangalore', 'State': 'Karnataka', 'Country': 'India', 'Latitude': '12.9612', 'Longitude': '74.8902'},
    {'IATA': 'NAG', 'Name': 'Dr. Babasaheb Ambedkar International', 'City': 'Nagpur', 'State': 'Maharashtra', 'Country': 'India', 'Latitude': '21.0922', 'Longitude': '79.0472'},
    {'IATA': 'IXZ', 'Name': 'Veer Savarkar International', 'City': 'Port Blair', 'State': 'Andaman and Nicobar Islands', 'Country': 'India', 'Latitude': '11.6410', 'Longitude': '92.7297'},
    {'IATA': 'TIR', 'Name': 'Tirupati Airport', 'City': 'Tirupati', 'State': 'Andhra Pradesh', 'Country': 'India', 'Latitude': '13.6325', 'Longitude': '79.5433'},
    {'IATA': 'VGA', 'Name': 'Vijayawada International', 'City': 'Vijayawada', 'State': 'Andhra Pradesh', 'Country': 'India', 'Latitude': '16.5304', 'Longitude': '80.7968'},
    {'IATA': 'CDP', 'Name': 'Kadapa Airport', 'City': 'Kadapa', 'State': 'Andhra Pradesh', 'Country': 'India', 'Latitude': '14.5100', 'Longitude': '78.7728'},
    {'IATA': 'RJA', 'Name': 'Rajahmundry Airport', 'City': 'Rajahmundry', 'State': 'Andhra Pradesh', 'Country': 'India', 'Latitude': '17.1104', 'Longitude': '81.8182'},
    {'IATA': 'VTZ', 'Name': 'Visakhapatnam International', 'City': 'Visakhapatnam', 'State': 'Andhra Pradesh', 'Country': 'India', 'Latitude': '17.7211', 'Longitude': '83.2245'},
    {'IATA': 'IXA', 'Name': 'Agartala Airport', 'City': 'Agartala', 'State': 'Tripura', 'Country': 'India', 'Latitude': '23.8870', 'Longitude': '91.2404'},
    {'IATA': 'IXI', 'Name': 'Lilabari Airport', 'City': 'Lilabari', 'State': 'Assam', 'Country': 'India', 'Latitude': '27.2955', 'Longitude': '94.0976'},
    {'IATA': 'IXS', 'Name': 'Silchar Airport', 'City': 'Silchar', 'State': 'Assam', 'Country': 'India', 'Latitude': '24.9129', 'Longitude': '92.9787'},
    {'IATA': 'IXD', 'Name': 'Bamrauli Airport', 'City': 'Allahabad', 'State': 'Uttar Pradesh', 'Country': 'India', 'Latitude': '25.4401', 'Longitude': '81.7339'},
    {'IATA': 'IXW', 'Name': 'Sonari Airport', 'City': 'Jamshedpur', 'State': 'Jharkhand', 'Country': 'India', 'Latitude': '22.8132', 'Longitude': '86.1688'},
    {'IATA': 'PAT', 'Name': 'Jay Prakash Narayan Airport', 'City': 'Patna', 'State': 'Bihar', 'Country': 'India', 'Latitude': '25.5913', 'Longitude': '85.0879'},
    {'IATA': 'IXJ', 'Name': 'Jammu Airport', 'City': 'Jammu', 'State': 'Jammu and Kashmir', 'Country': 'India', 'Latitude': '32.6891', 'Longitude': '74.8374'},
    {'IATA': 'IXL', 'Name': 'Kushok Bakula Rimpochee Airport', 'City': 'Leh', 'State': 'Ladakh', 'Country': 'India', 'Latitude': '34.1359', 'Longitude': '77.5465'},
    {'IATA': 'DED', 'Name': 'Jolly Grant Airport', 'City': 'Dehradun', 'State': 'Uttarakhand', 'Country': 'India', 'Latitude': '30.1897', 'Longitude': '78.1803'},
    {'IATA': 'PGH', 'Name': 'Pantnagar Airport', 'City': 'Pantnagar', 'State': 'Uttarakhand', 'Country': 'India', 'Latitude': '29.0334', 'Longitude': '79.4737'},
    {'IATA': 'HDO', 'Name': 'Hindon Airport', 'City': 'Ghaziabad', 'State': 'Uttar Pradesh', 'Country': 'India', 'Latitude': '28.7070', 'Longitude': '77.3586'},
    {'IATA': 'AGR', 'Name': 'Agra Airport', 'City': 'Agra', 'State': 'Uttar Pradesh', 'Country': 'India', 'Latitude': '27.1558', 'Longitude': '77.9609'},
    {'IATA': 'KNU', 'Name': 'Kanpur Airport', 'City': 'Kanpur', 'State': 'Uttar Pradesh', 'Country': 'India', 'Latitude': '26.4414', 'Longitude': '80.3649'},
    {'IATA': 'GOP', 'Name': 'Gorakhpur Airport', 'City': 'Gorakhpur', 'State': 'Uttar Pradesh', 'Country': 'India', 'Latitude': '26.7397', 'Longitude': '83.4497'},
    {'IATA': 'DBR', 'Name': 'Darbhanga Airport', 'City': 'Darbhanga', 'State': 'Bihar', 'Country': 'India', 'Latitude': '26.1928', 'Longitude': '85.9167'},
    {'IATA': 'RUP', 'Name': 'Rupsi Airport', 'City': 'Rupsi', 'State': 'Assam', 'Country': 'India', 'Latitude': '26.1397', 'Longitude': '89.9106'},
    {'IATA': 'IXT', 'Name': 'Pasighat Airport', 'City': 'Pasighat', 'State': 'Arunachal Pradesh', 'Country': 'India', 'Latitude': '28.0661', 'Longitude': '95.3356'},
    {'IATA': 'TEI', 'Name': 'Tezu Airport', 'City': 'Tezu', 'State': 'Arunachal Pradesh', 'Country': 'India', 'Latitude': '27.9412', 'Longitude': '96.1344'},
    {'IATA': 'SHL', 'Name': 'Shillong Airport', 'City': 'Shillong', 'State': 'Meghalaya', 'Country': 'India', 'Latitude': '25.7036', 'Longitude': '91.9787'},
    {'IATA': 'AJL', 'Name': 'Lengpui Airport', 'City': 'Aizawl', 'State': 'Mizoram', 'Country': 'India', 'Latitude': '23.8406', 'Longitude': '92.6197'},
    {'IATA': 'DMU', 'Name': 'Dimapur Airport', 'City': 'Dimapur', 'State': 'Nagaland', 'Country': 'India', 'Latitude': '25.8839', 'Longitude': '93.7711'},
    {'IATA': 'PYG', 'Name': 'Zero Airport', 'City': 'Along', 'State': 'Arunachal Pradesh', 'Country': 'India', 'Latitude': '28.1753', 'Longitude': '94.8025'},
    {'IATA': 'KJB', 'Name': 'Kurnool Airport', 'City': 'Kurnool', 'State': 'Andhra Pradesh', 'Country': 'India', 'Latitude': '15.7958', 'Longitude': '78.0661'},
    {'IATA': 'CNN', 'Name': 'Kannur International', 'City': 'Kannur', 'State': 'Kerala', 'Country': 'India', 'Latitude': '11.9186', 'Longitude': '75.5472'},
    {'IATA': 'CCJ', 'Name': 'Calicut International', 'City': 'Kozhikode', 'State': 'Kerala', 'Country': 'India', 'Latitude': '11.1368', 'Longitude': '75.9553'},
    {'IATA': 'IMF', 'Name': 'Imphal Airport', 'City': 'Imphal', 'State': 'Manipur', 'Country': 'India', 'Latitude': '24.7600', 'Longitude': '93.8967'},
    {'IATA': 'KBK', 'Name': 'Kushinagar Airport', 'City': 'Kushinagar', 'State': 'Uttar Pradesh', 'Country': 'India', 'Latitude': '26.7403', 'Longitude': '83.8881'},
    {'IATA': 'SAG', 'Name': 'Shirdi Airport', 'City': 'Shirdi', 'State': 'Maharashtra', 'Country': 'India', 'Latitude': '19.6886', 'Longitude': '74.3778'},
    {'IATA': 'GOX', 'Name': 'Mopa Airport', 'City': 'Goa', 'State': 'Goa', 'Country': 'India', 'Latitude': '15.7181', 'Longitude': '73.8081'},
    {'IATA': 'AYJ', 'Name': 'Ayodhya Airport', 'City': 'Ayodhya', 'State': 'Uttar Pradesh', 'Country': 'India', 'Latitude': '26.7531', 'Longitude': '82.1547'},
    {'IATA': 'STV', 'Name': 'Surat Airport', 'City': 'Surat', 'State': 'Gujarat', 'Country': 'India', 'Latitude': '21.1147', 'Longitude': '72.7417'},
    {'IATA': 'PNQ', 'Name': 'Pune Airport', 'City': 'Pune', 'State': 'Maharashtra', 'Country': 'India', 'Latitude': '18.5822', 'Longitude': '73.9197'},
    {'IATA': 'IXU', 'Name': 'Aurangabad Airport', 'City': 'Aurangabad', 'State': 'Maharashtra', 'Country': 'India', 'Latitude': '19.8627', 'Longitude': '75.3981'},
    {'IATA': 'IDR', 'Name': 'Devi Ahilya Bai Holkar Airport', 'City': 'Indore', 'State': 'Madhya Pradesh', 'Country': 'India', 'Latitude': '22.7218', 'Longitude': '75.8011'},
    {'IATA': 'BHO', 'Name': 'Raja Bhoj Airport', 'City': 'Bhopal', 'State': 'Madhya Pradesh', 'Country': 'India', 'Latitude': '23.2875', 'Longitude': '77.3374'},
    {'IATA': 'RDP', 'Name': 'Kazi Nazrul Islam Airport', 'City': 'Durgapur', 'State': 'West Bengal', 'Country': 'India', 'Latitude': '23.6225', 'Longitude': '87.2431'},
    {'IATA': 'JRH', 'Name': 'Jorhat Airport', 'City': 'Jorhat', 'State': 'Assam', 'Country': 'India', 'Latitude': '26.7315', 'Longitude': '94.1755'},
    {'IATA': 'TEZ', 'Name': 'Tezpur Airport', 'City': 'Tezpur', 'State': 'Assam', 'Country': 'India', 'Latitude': '26.7092', 'Longitude': '92.7847'},
    {'IATA': 'DIB', 'Name': 'Dibrugarh Airport', 'City': 'Dibrugarh', 'State': 'Assam', 'Country': 'India', 'Latitude': '27.4839', 'Longitude': '95.0169'},
    {'IATA': 'GAY', 'Name': 'Gaya Airport', 'City': 'Gaya', 'State': 'Bihar', 'Country': 'India', 'Latitude': '24.7443', 'Longitude': '84.9512'},
    {'IATA': 'PNY', 'Name': 'Puducherry Airport', 'City': 'Puducherry', 'State': 'Puducherry', 'Country': 'India', 'Latitude': '11.9680', 'Longitude': '79.8128'},
    {'IATA': 'TCR', 'Name': 'Tuticorin Airport', 'City': 'Tuticorin', 'State': 'Tamil Nadu', 'Country': 'India', 'Latitude': '8.7172', 'Longitude': '78.0256'},
    {'IATA': 'SXV', 'Name': 'Salem Airport', 'City': 'Salem', 'State': 'Tamil Nadu', 'Country': 'India', 'Latitude': '11.7833', 'Longitude': '78.0667'},
    {'IATA': 'AGX', 'Name': 'Agatti Airport', 'City': 'Agatti', 'State': 'Lakshadweep', 'Country': 'India', 'Latitude': '10.8275', 'Longitude': '72.1760'},
    {'IATA': 'IXG', 'Name': 'Belagavi Airport', 'City': 'Belagavi', 'State': 'Karnataka', 'Country': 'India', 'Latitude': '15.8593', 'Longitude': '74.6183'},
    {'IATA': 'IXX', 'Name': 'Bidar Airport', 'City': 'Bidar', 'State': 'Karnataka', 'Country': 'India', 'Latitude': '17.9081', 'Longitude': '77.4872'},
    {'IATA': 'HBX', 'Name': 'Hubli Airport', 'City': 'Hubli', 'State': 'Karnataka', 'Country': 'India', 'Latitude': '15.3173', 'Longitude': '75.0849'},
    {'IATA': 'GBI', 'Name': 'Gulbarga Airport', 'City': 'Gulbarga', 'State': 'Karnataka', 'Country': 'India', 'Latitude': '17.3297', 'Longitude': '76.8344'},
    {'IATA': 'MYQ', 'Name': 'Mysore Airport', 'City': 'Mysore', 'State': 'Karnataka', 'Country': 'India', 'Latitude': '12.2302', 'Longitude': '76.6558'},
    {'IATA': 'VDY', 'Name': 'Vidyanagar Airport', 'City': 'Toranagallu', 'State': 'Karnataka', 'Country': 'India', 'Latitude': '15.1747', 'Longitude': '76.6347'},
    {'IATA': 'RPR', 'Name': 'Swami Vivekananda Airport', 'City': 'Raipur', 'State': 'Chhattisgarh', 'Country': 'India', 'Latitude': '21.1804', 'Longitude': '81.7388'},
    {'IATA': 'JGB', 'Name': 'Jagdalpur Airport', 'City': 'Jagdalpur', 'State': 'Chhattisgarh', 'Country': 'India', 'Latitude': '19.0742', 'Longitude': '82.0367'},
    {'IATA': 'PAB', 'Name': 'Bilaspur Airport', 'City': 'Bilaspur', 'State': 'Chhattisgarh', 'Country': 'India', 'Latitude': '22.3367', 'Longitude': '82.1117'},
    {'IATA': 'JRG', 'Name': 'Jharsuguda Airport', 'City': 'Jharsuguda', 'State': 'Odisha', 'Country': 'India', 'Latitude': '21.9136', 'Longitude': '84.0503'},
    {'IATA': 'KLH', 'Name': 'Kolhapur Airport', 'City': 'Kolhapur', 'State': 'Maharashtra', 'Country': 'India', 'Latitude': '16.6647', 'Longitude': '74.2894'},
    {'IATA': 'SDW', 'Name': 'Sindhudurg Airport', 'City': 'Sindhudurg', 'State': 'Maharashtra', 'Country': 'India', 'Latitude': '16.0028', 'Longitude': '73.5264'},
    {'IATA': 'NDC', 'Name': 'Nanded Airport', 'City': 'Nanded', 'State': 'Maharashtra', 'Country': 'India', 'Latitude': '19.1831', 'Longitude': '77.3156'},
    {'IATA': 'GDB', 'Name': 'Gondia Airport', 'City': 'Gondia', 'State': 'Maharashtra', 'Country': 'India', 'Latitude': '21.5261', 'Longitude': '80.2903'},
    {'IATA': 'JLG', 'Name': 'Jalgaon Airport', 'City': 'Jalgaon', 'State': 'Maharashtra', 'Country': 'India', 'Latitude': '21.0469', 'Longitude': '75.7581'},
    {'IATA': 'ISK', 'Name': 'Nashik Airport', 'City': 'Nashik', 'State': 'Maharashtra', 'Country': 'India', 'Latitude': '19.9633', 'Longitude': '73.8076'},
    {'IATA': 'BDQ', 'Name': 'Vadodara Airport', 'City': 'Vadodara', 'State': 'Gujarat', 'Country': 'India', 'Latitude': '22.3362', 'Longitude': '73.2263'},
    {'IATA': 'DIU', 'Name': 'Diu Airport', 'City': 'Diu', 'State': 'Dadra and Nagar Haveli & Daman and Diu', 'Country': 'India', 'Latitude': '20.7131', 'Longitude': '70.9211'},
    {'IATA': 'BHU', 'Name': 'Bhavnagar Airport', 'City': 'Bhavnagar', 'State': 'Gujarat', 'Country': 'India', 'Latitude': '21.7522', 'Longitude': '72.1850'},
    {'IATA': 'IXK', 'Name': 'Keshod Airport', 'City': 'Keshod', 'State': 'Gujarat', 'Country': 'India', 'Latitude': '21.3172', 'Longitude': '70.2703'},
    {'IATA': 'PBD', 'Name': 'Porbandar Airport', 'City': 'Porbandar', 'State': 'Gujarat', 'Country': 'India', 'Latitude': '21.6486', 'Longitude': '69.6572'},
    {'IATA': 'JGA', 'Name': 'Jamnagar Airport', 'City': 'Jamnagar', 'State': 'Gujarat', 'Country': 'India', 'Latitude': '22.4655', 'Longitude': '70.0125'},
    {'IATA': 'IXY', 'Name': 'Kandla Airport', 'City': 'Kandla', 'State': 'Gujarat', 'Country': 'India', 'Latitude': '23.1128', 'Longitude': '70.1003'},
    {'IATA': 'BHJ', 'Name': 'Bhuj Airport', 'City': 'Bhuj', 'State': 'Gujarat', 'Country': 'India', 'Latitude': '23.2878', 'Longitude': '69.6703'},
    {'IATA': 'REW', 'Name': 'Rewa Airport', 'City': 'Rewa', 'State': 'Madhya Pradesh', 'Country': 'India', 'Latitude': '24.5031', 'Longitude': '81.2200'},
    {'IATA': 'GWL', 'Name': 'Gwalior Airport', 'City': 'Gwalior', 'State': 'Madhya Pradesh', 'Country': 'India', 'Latitude': '26.2933', 'Longitude': '78.2278'},
    {'IATA': 'JLR', 'Name': 'Jabalpur Airport', 'City': 'Jabalpur', 'State': 'Madhya Pradesh', 'Country': 'India', 'Latitude': '23.1778', 'Longitude': '80.0520'},
    {'IATA': 'UDR', 'Name': 'Maharana Pratap Airport', 'City': 'Udaipur', 'State': 'Rajasthan', 'Country': 'India', 'Latitude': '24.6177', 'Longitude': '73.8961'},
    {'IATA': 'JSA', 'Name': 'Jaisalmer Airport', 'City': 'Jaisalmer', 'State': 'Rajasthan', 'Country': 'India', 'Latitude': '26.8889', 'Longitude': '70.8647'},
    {'IATA': 'JDH', 'Name': 'Jodhpur Airport', 'City': 'Jodhpur', 'State': 'Rajasthan', 'Country': 'India', 'Latitude': '26.2511', 'Longitude': '73.0489'},
    {'IATA': 'BKB', 'Name': 'Nal Airport', 'City': 'Bikaner', 'State': 'Rajasthan', 'Country': 'India', 'Latitude': '28.0706', 'Longitude': '73.2072'},
    {'IATA': 'KQH', 'Name': 'Kishangarh Airport', 'City': 'Ajmer', 'State': 'Rajasthan', 'Country': 'India', 'Latitude': '26.6014', 'Longitude': '74.8142'},
    {'IATA': 'DHM', 'Name': 'Kangra Airport', 'City': 'Kangra', 'State': 'Himachal Pradesh', 'Country': 'India', 'Latitude': '32.1651', 'Longitude': '76.2634'},
    {'IATA': 'KUU', 'Name': 'Kullu Manali Airport', 'City': 'Kullu', 'State': 'Himachal Pradesh', 'Country': 'India', 'Latitude': '31.8767', 'Longitude': '77.1542'},
    {'IATA': 'DGH', 'Name': 'Deoghar Airport', 'City': 'Deoghar', 'State': 'Jharkhand', 'Country': 'India', 'Latitude': '24.4497', 'Longitude': '86.7031'},
    {'IATA': 'COH', 'Name': 'Cooch Behar Airport', 'City': 'Cooch Behar', 'State': 'West Bengal', 'Country': 'India', 'Latitude': '26.3306', 'Longitude': '89.4672'},
    {'IATA': 'HSS', 'Name': 'Hisar Airport', 'City': 'Hisar', 'State': 'Haryana', 'Country': 'India', 'Latitude': '29.1792', 'Longitude': '75.7553'},
    {'IATA': 'DBD', 'Name': 'Dhanbad Airport', 'City': 'Dhanbad', 'State': 'Jharkhand', 'Country': 'India', 'Latitude': '23.8342', 'Longitude': '86.4253'},
    {'IATA': 'HJR', 'Name': 'Khajuraho Airport', 'City': 'Khajuraho', 'State': 'Madhya Pradesh', 'Country': 'India', 'Latitude': '24.8172', 'Longitude': '79.9186'},
    {'IATA': 'AVT', 'Name': 'Coimbatore International', 'City': 'Coimbatore', 'State': 'Tamil Nadu', 'Country': 'India', 'Latitude': '11.0296', 'Longitude': '77.0434'},
    {'IATA': 'IXM', 'Name': 'Madurai Airport', 'City': 'Madurai', 'State': 'Tamil Nadu', 'Country': 'India', 'Latitude': '9.8344', 'Longitude': '78.0933'},
    {'IATA': 'IXH', 'Name': 'Kailashahar Airport', 'City': 'Kailashahar', 'State': 'Tripura', 'Country': 'India', 'Latitude': '24.3300', 'Longitude': '92.0100'},
    {'IATA': 'IXQ', 'Name': 'Kamalpur Airport', 'City': 'Kamalpur', 'State': 'Tripura', 'Country': 'India', 'Latitude': '24.1300', 'Longitude': '91.8100'},
    {'IATA': 'IXN', 'Name': 'Khowai Airport', 'City': 'Khowai', 'State': 'Tripura', 'Country': 'India', 'Latitude': '24.0600', 'Longitude': '91.6000'},
    {'IATA': 'PXN', 'Name': 'Pakyong Airport', 'City': 'Gangtok', 'State': 'Sikkim', 'Country': 'India', 'Latitude': '27.2906', 'Longitude': '88.5856'},
    {'IATA': 'NMIA', 'Name': 'Navi Mumbai International', 'City': 'Navi Mumbai', 'State': 'Maharashtra', 'Country': 'India', 'Latitude': '18.9883', 'Longitude': '73.3103'},
    {'IATA': 'WGC', 'Name': 'Warangal Airport', 'City': 'Warangal', 'State': 'Telangana', 'Country': 'India', 'Latitude': '18.0000', 'Longitude': '79.6000'},
    {'IATA': 'TRZ', 'Name': 'Tiruchirappalli International', 'City': 'Tiruchirappalli', 'State': 'Tamil Nadu', 'Country': 'India', 'Latitude': '10.7654', 'Longitude': '78.7097'},
    {'IATA': 'RQY', 'Name': 'Shimoga Airport', 'City': 'Shimoga', 'State': 'Karnataka', 'Country': 'India', 'Latitude': '13.9194', 'Longitude': '75.5492'},
    {'IATA': 'RAJ', 'Name': 'Rajkot International', 'City': 'Rajkot', 'State': 'Gujarat', 'Country': 'India', 'Latitude': '22.3092', 'Longitude': '70.7794'},
    {'IATA': 'SLV', 'Name': 'Shimla Airport', 'City': 'Shimla', 'State': 'Himachal Pradesh', 'Country': 'India', 'Latitude': '31.0819', 'Longitude': '77.0681'},
]

if __name__ == "__main__":
    import os
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    output_path = os.path.join(project_root, 'public', 'data', 'Major_Airports.csv')
    
    fieldnames = ['IATA', 'Name', 'City', 'State', 'Country', 'Latitude', 'Longitude']
    
    with open(output_path, 'w', newline='', encoding='utf-8') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(major_airports)
    
    print(f"Created CSV with {len(major_airports)} major airports")
    print(f"Saved to: {output_path}")

